"""LiteLLM 模型名的 provider 路由与解析。"""

DEFAULT_RERANK_PROVIDER = "jina_ai"
# Static LiteLLM provider prefixes avoid importing LiteLLM during name parsing.
LITELLM_PROVIDER_PREFIXES = {
    "a2a",
    "a2a_agent",
    "ai21",
    "ai21_chat",
    "aiml",
    "aiohttp_openai",
    "amazon_nova",
    "anthropic",
    "anthropic_text",
    "apertis",
    "assemblyai",
    "auto_router",
    "aws_polly",
    "azure",
    "azure_ai",
    "azure_text",
    "baseten",
    "bedrock",
    "bedrock_mantle",
    "black_forest_labs",
    "bytez",
    "cerebras",
    "charity_engine",
    "chatgpt",
    "chutes",
    "clarifai",
    "cloudflare",
    "codestral",
    "cohere",
    "cohere_chat",
    "cometapi",
    "compactifai",
    "cursor",
    "custom",
    "custom_openai",
    "dashscope",
    "databricks",
    "datarobot",
    "deepgram",
    "deepinfra",
    "deepseek",
    "docker_model_runner",
    "dotprompt",
    "elevenlabs",
    "empower",
    "fal_ai",
    "featherless_ai",
    "fireworks_ai",
    "friendliai",
    "galadriel",
    "gemini",
    "gigachat",
    "github",
    "github_copilot",
    "gradient_ai",
    "groq",
    "helicone",
    "heroku",
    "hosted_vllm",
    "huggingface",
    "humanloop",
    "hyperbolic",
    "inception",
    "infinity",
    "jina_ai",
    "lambda_ai",
    "langflow",
    "langfuse",
    "langgraph",
    "lemonade",
    "libertai",
    "litellm_agent",
    "litellm_proxy",
    "llamafile",
    "lm_studio",
    "manus",
    "maritalk",
    "meta_llama",
    "milvus",
    "minimax",
    "mistral",
    "modelscope",
    "moonshot",
    "morph",
    "nano-gpt",
    "nebius",
    "neosantara",
    "nlp_cloud",
    "novita",
    "nscale",
    "nvidia_nim",
    "nvidia_riva",
    "oci",
    "ollama",
    "ollama_chat",
    "oobabooga",
    "openai",
    "openai_like",
    "openrouter",
    "ovhcloud",
    "parasail",
    "perplexity",
    "petals",
    "pg_vector",
    "pinstripes",
    "poe",
    "predibase",
    "publicai",
    "ragflow",
    "recraft",
    "reducto",
    "replicate",
    "runwayml",
    "s3_vectors",
    "sagemaker",
    "sagemaker_chat",
    "sagemaker_nova",
    "sambanova",
    "sap",
    "scaleway",
    "snowflake",
    "soniox",
    "stability",
    "synthetic",
    "tensormesh",
    "text-completion-codestral",
    "text-completion-inception",
    "text-completion-openai",
    "together_ai",
    "topaz",
    "triton",
    "v0",
    "vercel_ai_gateway",
    "vertex_ai",
    "vertex_ai_beta",
    "vllm",
    "volcengine",
    "voyage",
    "wandb",
    "watsonx",
    "watsonx_text",
    "xai",
    "xiaomi_mimo",
    "xinference",
    "zai",
}


def litellm_model_name(provider: str | None, model: str) -> str:
    """Return a LiteLLM-routable model name without changing stored config names."""
    cleaned_model = model.strip()
    cleaned_provider = (provider or "").strip().strip("/")
    if not cleaned_model or not cleaned_provider:
        return cleaned_model

    first_segment = cleaned_model.split("/", 1)[0]
    if first_segment in LITELLM_PROVIDER_PREFIXES:
        return cleaned_model
    return f"{cleaned_provider}/{cleaned_model}"


def litellm_rerank_model_name(model: str) -> str:
    """Return a LiteLLM-routable model for Cohere/Jina-style rerank endpoints."""
    return litellm_model_name(DEFAULT_RERANK_PROVIDER, model)
